name: spaceblocks_dev
channels:
  - conda-forge
  - bioconda

dependencies:
  # Base snakemake environment
  - snakemake>=9.13

  # Formatting and linting tools
  - pre_commit
  - bioconda::snakefmt

  # Documentation tools
  - mkdocs
  - pymdown-extensions
  - mkdocs-material

  # Graphviz (for dot)
  - graphviz
